name: Lint, Typecheck, Unittest

on:
  workflow_call:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  commitlint:
    name: "Commit linter"
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install commitlint
        run: npm install -D @commitlint/cli @commitlint/config-conventional
      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  lint-and-typecheck:
    name: "Lint and Type check"
    runs-on: "ubuntu-latest"
    needs:
      - commitlint
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          architecture: 'x64'

      - name: Install Deps
        run: |
          sudo snap install charmcraft --channel latest/stable --classic
          sudo snap install just --classic
          sudo snap install astral-uv --classic

      - name: "Run lint checks"
        run: |
          just repo lint

      - name: "Run typechecker"
        run: |
          just repo typecheck
